use crate::types::icrc7;

pub use icrc7::icrc7_collection_metadata::{Args as CollectionMetadataArgs, Response as CollectionMetadataResponse};
pub use icrc7::icrc7_symbol::{Args as SymbolArgs, Response as SymbolResponse};
pub use icrc7::icrc7_name::{Args as NameArgs, Response as NameResponse};
pub use icrc7::icrc7_description::{Args as DescriptionArgs, Response as DescriptionResponse};
pub use icrc7::icrc7_logo::{Args as LogoArgs, Response as LogoResponse};
pub use icrc7::icrc7_total_supply::{Args as TotalSupplyArgs, Response as TotalSupplyResponse};
pub use icrc7::icrc7_supply_cap::{Args as SupplyCapArgs, Response as SupplyCapResponse};
pub use icrc7::icrc7_max_query_batch_size::{Args as MaxQueryBatchSizeArgs, Response as MaxQueryBatchSizeResponse};
pub use icrc7::icrc7_max_update_batch_size::{Args as MaxUpdateBatchSizeArgs, Response as MaxUpdateBatchSizeResponse};
pub use icrc7::icrc7_default_take_value::{Args as DefaultTakeValueArgs, Response as DefaultTakeValueResponse};
pub use icrc7::icrc7_max_take_value::{Args as MaxTakeValueArgs, Response as MaxTakeValueResponse};
pub use icrc7::icrc7_max_memo_size::{Args as MaxMemoSizeArgs, Response as MaxMemoSizeResponse};
pub use icrc7::icrc7_atomic_batch_transfers::{Args as AtomicBatchTransfersArgs, Response as AtomicBatchTransfersResponse};
pub use icrc7::icrc7_tx_window::{Args as TxWindowArgs, Response as TxWindowResponse};
pub use icrc7::icrc7_permitted_drift::{Args as PermittedDriftArgs, Response as PermittedDriftResponse};
pub use icrc7::icrc7_token_metadata::{Args as TokenMetadataArgs, Response as TokenMetadataResponse};
pub use icrc7::icrc7_owner_of::{Args as OwnerOfArgs, Response as OwnerOfResponse};
pub use icrc7::icrc7_balance_of::{Args as BalanceOfArgs, Response as BalanceOfResponse};
pub use icrc7::icrc7_tokens::{Args0 as TokensArgs0, Args1 as TokensArgs1, Response as TokensResponse};
pub use icrc7::icrc7_tokens_of::{Args0 as TokensOfArgs0, Args1 as TokensOfArgs1, Args2 as TokensOfArgs2, Response as TokensOfResponse};